name: "Terraform Examples Validation Coverage"

on:
  pull_request:
    types:
    - opened
    branches:
    - main
    paths:
    - examples/**

jobs:

  coverage:
    name: 'Examples Validation Coverage'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ">=1.6.0"

    - name: Execute Tests
      run: make precheck

